-- v15 — one pharmacy per WhatsApp number
--
-- wa_jid and gowa_device_id have carried partial unique indexes since v8. wa_number did
-- not, and the gap was not theoretical: after 254777602338 was converted into the platform
-- line, TWO rows claimed that number at once -- the new Pharma OS row, and New Lemuma's
-- stale value left behind because the conversion deliberately cleared only wa_jid and
-- gowa_device_id.
--
-- Nothing failed loudly, which is the problem. A `where wa_number = %s` lookup simply
-- returns whichever row Postgres reaches first. tenant.resolve_pharmacy_by_device() has
-- exactly such a lookup as its third fallback, and it was unreachable for that JID only
-- because resolve() matches wa_jid and returns kind='platform' before the fallback is
-- consulted. That is luck, not design, and it stops being luck the moment a pharmacy
-- rebinds to a number another row still holds -- which is precisely what ./run.sh rebind
-- is for.
--
-- Partial (WHERE NOT NULL) so the many pharmacies with no number yet are unaffected, and
-- so a released tenant -- whose wa_number is cleared on unpair -- does not block the next
-- one. Same shape as pharmacies_wa_jid_uniq and pharmacies_gowa_device_id_uniq.
create unique index if not exists pharmacies_wa_number_uniq
  on pharmacies (wa_number) where wa_number is not null;
